// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import <Foundation/Foundation.h>
@class NTVCoreApplicationCore;


@interface NTVCoreApplicationCore : NSObject

+ (nullable NTVCoreApplicationCore *)shared;

- (double)multiply:(double)value1
            value2:(double)value2;

- (nonnull NSString *)getVersion;

@end
