// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include "djinni/wasm/djinni_wasm.hpp"
#include "nativium/core/ApplicationCore.hpp"

namespace djinni_generated {

struct NTVCoreApplicationCore : ::djinni::JsInterface<::nativium::core::ApplicationCore, NTVCoreApplicationCore> {
    using CppType = std::shared_ptr<::nativium::core::ApplicationCore>;
    using CppOptType = std::shared_ptr<::nativium::core::ApplicationCore>;
    using JsType = em::val;
    using Boxed = NTVCoreApplicationCore;

    static CppType toCpp(JsType j) { return _fromJs(j); }
    static JsType fromCppOpt(const CppOptType& c) { return {_toJs(c)}; }
    static JsType fromCpp(const CppType& c) { return fromCppOpt(c); }

    static em::val cppProxyMethods();

    static em::val shared();
    static double multiply(const CppType& self, double w_value1,double w_value2);
    static std::string getVersion(const CppType& self);

};

}  // namespace djinni_generated
